//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _19_RestaurantTableCurrentStatusProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tables
    {
        public int TableId { get; set; }
        public string TableNumber { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
